// <auto-generated />
using Core.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Core.Migrations
{
    [DbContext(typeof(QLSVContext))]
    partial class QLSVContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.15")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Models.Love", b =>
                {
                    b.Property<string>("MaLove")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GVCN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Siso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLove")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLove");

                    b.ToTable("loves");
                });

            modelBuilder.Entity("Core.Models.SinhVien", b =>
                {
                    b.Property<string>("msv")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("diachi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sdt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tuoi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("msv");

                    b.ToTable("sinhViens");
                });

            modelBuilder.Entity("LoveSinhVien", b =>
                {
                    b.Property<string>("LovesMaLove")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SinhViensmsv")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LovesMaLove", "SinhViensmsv");

                    b.HasIndex("SinhViensmsv");

                    b.ToTable("LoveSinhVien");
                });

            modelBuilder.Entity("LoveSinhVien", b =>
                {
                    b.HasOne("Core.Models.Love", null)
                        .WithMany()
                        .HasForeignKey("LovesMaLove")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.SinhVien", null)
                        .WithMany()
                        .HasForeignKey("SinhViensmsv")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
